### ISSUE TITLE
uacme exit codes with systemd

### ISSUE THREAD

**Issue by pmjdebruijn** [ndilieto/uacme#18]
uacme's exit codes aren't ideal for use as a systemd oneshot service:

0 Success
1 Certificate not reissued because it is still current
2 Failure (syntax or usage error; configuration error; processing failure; unexpected error).

By default systemd considers a nonzero exit code as a failure:
https://freedesktop.org/software/systemd/man/systemd.exec.html#id-1.20.4

While systemd has facilities to deal with this like SuccessExitStatus= it's far from ideal, as the status code lookup still shows 1/FAILURE. As exit 1 is the standard failure exit code for libc.

**Comment by ndilieto** [comment]
You seem unaware that exit codes other than 0 or 1 are commonly used by several unix programs. Just an example from the 'grep' manpage at http://www.man7.org/linux/man-pages/man1/grep.1.html#EXIT_STATUS

> Normally the exit status is 0 if a line is selected, 1 if no lines were selected, and 2 if an error occurred.

I'd kindly ask you to refrain from wasting more of my scarce time in the future.
