### ISSUE TITLE
Error recognition fails if parameter is present in reply's "Content-Type" header

### ISSUE THREAD

**Issue by andwei** [ndilieto/uacme#22]
Hi,

fooling around with uacme and pebble I noticed that account creation always fails. I found that pebble returns the header `Content-Type: application/probjem+json; charset=utf-8` in its error replies, which is perfectly valid according to https://tools.ietf.org/html/rfc7231#section-3.1.1.1

Due to using strcasecmp for comparision, this fails on several places, including [account creation](https://github.com/ndilieto/uacme/blob/18095187f18eb6faa234dcacefa7b7b21f720b64/uacme.c#L412), which is then wrongly aborted.

I guess the most simple fix would be to just use strncasecmp on those 4 occasions.

**Comment by ndilieto** [comment]
Thanks for spotting and reporting this. I normally test agains the staging let's encrypt endpoint and that doesn't behave like pebble. Nevertheless, it's a bug and I fixed it in release 1.2.3
