### ISSUE TITLE
How to work correctly with dns-01 in hook?

### ISSUE THREAD

**Issue by MrSorcus** [ndilieto/uacme#3]
In the hook script what must i paste into TXT record?
`TOKEN` or `AUTH`? Or both?
Sorry if question is very silly.

**Comment by ndilieto** [comment]
From the man page: 

>  AUTH    The key authorization (for dns-01 already converted to the base64-encoded SHA256 digest format to be provisioned as _acme-challenge DNS TXT record).

Meaning you must just put the content of AUTH in the _acme-challenge.your.domain.com TXT record.
