### ISSUE TITLE
Consider migrating to scdoc for man pages

### ISSUE THREAD

**Issue by ddevault** [ndilieto/uacme#31]
asciidoc is a pretty heavy dependency - it pulls in LaTeX on Debian, for example - and there are much simpler ways to generate man pages.

Would you consider my tool, scdoc?

https://git.sr.ht/~sircmpwn/scdoc

It has zero dependencies other than a POSIX system and a C99 compiler.

**Comment by ndilieto** [comment]
asciidoc on debian recommends ascidoc-dblatex but doesn't require it so it's not as bad as it could be. I've been thinking of moving to another system but it's at the very bottom of my todo list.

scdoc is nice and simple, which I like. But, correct me if I am wrong, it doesn't do html formatting which I need for the online manpages. And man->html conversion with groff sucks. So I am afraid I'm going to decline your offer.

Thanks anyway for your suggestion.

**Comment by ddevault** [comment]
No problem, cheers!
