### ISSUE TITLE
nsupdate.sh: ns_getdomain selects wrong server to send updates

### ISSUE THREAD

**Issue by sthen** [ndilieto/uacme#32]
I just came across uacme when finally getting around to move my dns-01 setup across from some ACMEv1-only software. Thanks for writing it - I like the balance of useful features without being over-complex. It seems I picked a good time because nsupdate.sh was added recently - I ran into a few things I needed to change to get that to work for me, I'm happy to split into PRs if you like but I thought I'd discuss here first.

When trying to identify which servers should receive updates, ns_getdomain picks the last two components of the domain name (foo.bar.example.org -> example.org). This is fine for simple "domain.tld" cases with no subdomains, but fails for country TLDs like .uk where many names are registered under .co.uk/.org.uk/.net.uk, or where a zone is delegated privately.

I'm using this instead, which I think should handle all cases, at the expense of another callout to dig:

```
ns_getdomain()
{
    local domain=$1

    [ -n "$domain" ] || return
    set -- $($DIG +noall +authority "$domain" SOA 2>/dev/null)

    echo $1
}
```

A couple of other smaller things I noticed,

- the various calls to dig using the system's default nameserver use -k RNDC_KEY, which fails at least in some situations - should those be dropped and RNDC_KEY just used for nsupdate calls?

- there's a bashism ${res//\"/} in ns_ispresent but the hashbang line is for /bin/sh (and the other scripts look like plain shell). It could be rewritten like this, or would it be preferable to change to a bash #!?

```
    for NS in $nameservers; do
        OLDIFS="${IFS}"
        IFS='.'
        set -- $($DIG +short "@$NS" "$fqhn" TXT 2>/dev/null)
        IFS="${OLDIFS}"
        [ "$*" = "$expect" ] || return 1
    done
```

- ns_gethostname has ${ret:1} which could be replaced with ${ret#?}, but the function is unused anyway, should it just be dropped?

**Comment by ndilieto** [comment]
I think you are right. nsupdate.sh was contributed by Michel Stam, so let's ask him what he thinks before deciding how to fix it.

@MichelStam have you got any comments on this?

**Comment by MichelStam** [comment]
Hi,

Good review.

- I agree that subdomains are not handled as best as they should. Intention is to extract the NS records to see which nameservers need to be tested for the presence/absence of the acme record. The dig for the SOA record is to verify which server qualifies as the primary NS and will get the nsupdate command.
- Dropping RNDC_KEY entirely would break multi-view DNS setups. By utilising the key you can force the correct view to be shown to dig.
- Script was written for bash, so probably changing it to bash would be preferable
- gethostname is indeed not used anymore. It was in an older version of the script and could be removed.

Cheers,

Michel
