### ISSUE TITLE
add option to define custom certificate subdirectory (?)

### ISSUE THREAD

**Issue by andwei** [ndilieto/uacme#33]
Hi,

would you consider support for an option by which the default "IDENTIFIER" part in determining the storage location for the certificate to be issued can be replaced by a custom, arbitrary value?

While it does probably make not too much sense to have multiple certificates with the same first identifier/common name, it is not strictly invalid and would not work well/at all with the default paths.

I'm in a situation where the actual certificate configuration is outside of my control and I would like to not have to restrict the choice of certificate (subject alternatives) names and at the same time avoid any potential collisions, which I currently do by using a different unique identifier.

PR using "-u" for this: #34

**Comment by ndilieto** [comment]
Since version 1.3 uacme supports issuing certificates with a user supplied CSR file, which you could generate yourself according to your requirements - see https://ndilieto.github.io/uacme/uacme.html#_usage for details. If you supply your own CSR file, you can put any identifiers you like in the common name and subject alt names; uacme will just parse the CSR and submit them to the ACME server. Would that work for you?

**Comment by andwei** [comment]
Ahh. I noticed the feature was added but haven't looked into it in detail, yet. I had switching to using CSRs on my mind anyways, so maybe I take that additional fact as a motivation.

Thanks for pointing it out, I guess it would work for me if you are not so enthusiastic about the custom-cert-subdir suggestion :)

**Comment by ndilieto** [comment]
Your patch is quite straightforward, but as usual feature creep is a slippery slope. The CSR feature was requested by another user who couldn't use uacme without it (his Cisco router generates signed CSRs only and doesn't give access to the private key). So if it could work for you I'd rather not merge your code. CSRs don't expire so you can generate it offline and reuse it over and over again.

**Comment by andwei** [comment]
No worries at all. Thanks for the immediate response. I think going with the CSRs is actually a better overall solution anyways.
