### ISSUE TITLE
ualpn --daemon parent is killed by SIGPIPE in cleanup_and_exit()

### ISSUE THREAD

**Issue by ssb83** [ndilieto/uacme#36]
Launching ualpn with --daemon option makes it crash with SIGPIPE just before successful exit of the parent process.  This results in returning error status to shell, while the actual daemon is started successfully.

**Comment by ndilieto** [comment]
Which OS are you on? Please include version. 

Launch uacme with -v -v -v -l /tmp/uacme.log and post the log file here

**Comment by ssb83** [comment]
Debian, both stable and sid.

gdb session:
(gdb) run -vvv -l ualpn.log  -d -c 127.0.0.1@4443
Starting program: /opt/src/uacme/ualpn -vvv -l ualpn.log  -d -c 127.0.0.1@4443
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
May 30 21:49:27 ualpn/17848: [NOTICE] logging to file ualpn.log
[Detaching after fork from child process 17852]

Program received signal SIGPIPE, Broken pipe.
0x00007ffff7f83dd3 in __libc_write (fd=5, buf=0x5555555696f8, nbytes=3)
    at ../sysdeps/unix/sysv/linux/write.c:26
26	../sysdeps/unix/sysv/linux/write.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7f83dd3 in __libc_write (fd=5, buf=0x5555555696f8, nbytes=3)
    at ../sysdeps/unix/sysv/linux/write.c:26
#1  0x0000555555561e0a in cleanup_and_exit (stage=0, return_code=0) at ualpn.c:3624
#2  0x00005555555645f4 in main (argc=7, argv=0x7fffffffe6a8) at ualpn.c:4386
(gdb) f 1
#1  0x0000555555561e0a in cleanup_and_exit (stage=0, return_code=0) at ualpn.c:3624
3624	                    if (write(g.pipefd[1], "ERR", 3) == 3)
(gdb) 


ualpn.log:
May 30 21:49:27 ualpn/17852: [NOTICE] control interface listening to unix:///var/run/ualpn.sock
May 30 21:49:27 ualpn/17852: [INFO] open file descriptor limit: 4096
May 30 21:49:27 ualpn/17852: [INFO] libev initialized (backend EPOLL)
May 30 21:49:27 ualpn/17852: [NOTICE] frontend listening to :::443
May 30 21:49:27 ualpn/17852: [NOTICE] frontend listening to 0.0.0.0:443
May 30 21:49:27 ualpn/17848: [NOTICE] daemon started (pid 17852)
May 30 21:49:27 ualpn/17852: [INFO] new worker 17853 started
May 30 21:49:27 ualpn/17853: [NOTICE] new worker starting
May 30 21:49:27 ualpn/17852: [INFO] new worker 17854 started
May 30 21:49:27 ualpn/17854: [NOTICE] new worker starting

**Comment by ndilieto** [comment]
Thanks for spotting it. It should be fixed now. Let me know please so I make a new release

**Comment by ssb83** [comment]
Yes, it is fixed for me, thanks!

**Comment by ndilieto** [comment]
Ok, thanks. Just released as 1.4.1.
