### ISSUE TITLE
Could not create new account on OpenWrt 

### ISSUE THREAD

**Issue by weixie4** [ndilieto/uacme#38]
Hi 

This is less of an issue than a request for help because I could barely find any documentation for getting uacme to work on OpenWrt.

I successfully compiled and installed the uacme package for OpenWrt from its package source at https://github.com/openwrt/packages/tree/master/net/uacme

Then I tried to create a new account:
`# uacme -v -c /etc/acme/ new`
uacme: version 1.2.1 starting on Wed, 28 Oct 2020 06:28:46 -0700
uacme: created directory /etc/acme//private
uacme: loading key from /etc/acme//private/key.pem
uacme: /etc/acme//private/key.pem not found
uacme: generating new 2048-bit RSA key
uacme: key saved to /etc/acme//private/key.pem
uacme: fetching directory at https://acme-v02.api.letsencrypt.org/directory
uacme: creating new account at https://acme-v02.api.letsencrypt.org/acme/new-acct
uacme: type 'y' to accept the terms at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
y
uacme: account created at https://acme-v02.api.letsencrypt.org/acme/acct/100577813
 uacme -v -c /etc/acme/ new

However, open the link https://acme-v02.api.letsencrypt.org/acme/acct/100577813, I got the following error:
{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Method not allowed",
  "status": 405
} 

Could I get any help here?
Thanks!
Wei

**Comment by ndilieto** [comment]
This is normal, you can't just open the account link with a browser. ACME URLs can only be used by a client (such as uacme) that talks the ACME protocol, which involves cryptographic signatures.

Please, read the tutorial at https://github.com/ndilieto/uacme#getting-started
