### ISSUE TITLE
please add options to specify keys & certificates locations

### ISSUE THREAD

**Issue by quasis** [ndilieto/uacme#42]
The feature becomes critical when uacme is dockerized, due to need in secret management and certificate sharing.

**Comment by ndilieto** [comment]
RTFM: https://ndilieto.github.io/uacme/uacme.html

> -c, --confdir CONFDIR
>
>    Use configuration directory CONFDIR (default /etc/ssl/uacme). The structure is as follows (multiple IDENTIFIERs allowed)
>
>    CONFDIR/private/key.pem
>
>        ACME account private key
>    CONFDIR/private/IDENTIFIER/key.pem
>
>        certificate key for IDENTIFIER
>    CONFDIR/IDENTIFIER/cert.pem
>
>        certificate for IDENTIFIER

**Comment by quasis** [comment]
Yep, I'm aware of CONFDIR. It is not flexible enough for a cloud application. For example, the file structure might be as follows:

- /run/secrets/account_key.pem
- /run/secrets/domain.com_key.pem
- /etc/ssl/domain.com/cert.pem

There are workarounds of course, but they unnecessarily complicate the code.

**Comment by ndilieto** [comment]
You can easily achieve any layout you wish with symbolic links. In your case,

```
ln -s /etc/ssl/uacme/private/key.pem /run/secrets/account_key.pem
ln -s /etc/ssl/uacme/private/domain.com/key.pem /run/secrets/domain.com_key.pem
ln -s /etc/ssl/uacme/domain.com/cert.pem /etc/ssl/domain.com/cert.pem
```
If you don't like the default prefix (/etc/ssl/uacme), change it with `-c /run/uacme` for example.
