### ISSUE TITLE
No joy  with install on Raspbian / Buster

### ISSUE THREAD

**Issue by CvW** [ndilieto/uacme#43]
Good morning,

I tried installing UACME  on my Pi 4 (running Buster). I ran into two installation issues so far when I executed the "./configure --disable-maintainer-mode"  command. 
- The first time, it failed due to a lack of libcurl. I installed that  and re-ran the installation script. 
- The installer made it past libcurl but  then got caught on GNUTLS missing. So I installed that too, via "sudo apt-get install gnutls-bin". The  installer script still stalls and errors out, claiming that a suitable GNUTLS has not been installed. 

According to the GNUTLS installer, version 3.6.7 was installed "Setting up gnutls-bin (3.6.7-4+deb10u6) ..."
Per the UACME installer, "checking for GnuTLS >= 3.3.30... no" followed by "configure: error: gnutls not found"

I must be doing something wrong so I wonder if you  could make a suggestion re: GNUTLS or the version of LIBCURL that should be installed as a pre-requisite to installing UACME. I would also like to make the suggestion to reference these and any  other packages that must be installed before UACME to make the process easier for newbies like me. Thank you  for writing UACME!

Constantin

**Comment by ndilieto** [comment]
You need to install the development package, which is libgnutls28-dev

Also note, uacme is in raspbian bullseye: http://mirrordirector.raspbian.org/raspbian/pool/main/u/uacme
