### ISSUE TITLE
FYI: httpd-challenge-hook.sh

### ISSUE THREAD

**Issue by jirutka** [ndilieto/uacme#44]
You might be interested to know that I wrote a http-01 challenge hook script that is designed for the case when you don’t need/wanna continuously run a (full-blown) web server (e.g. domain for just OpenVPN, PostgreSQL, …). [Read more…](https://github.com/jirutka/muacme#httpd-challenge-hooksh)

**Comment by ndilieto** [comment]
Ok thanks.
