### ISSUE TITLE
support for --reuse-key

### ISSUE THREAD

**Issue by clandmeter** [ndilieto/uacme#5]
Hi, uacme looks very interesting to me but i could not find any information in the docs about the lifecycle of the key, I guess its renewed on renew? If so is it possible to a use or create similar option as certbot uses? ie --reuse-key.

**Comment by ndilieto** [comment]
read the manual at https://ndilieto.github.io/uacme/

> If the account private key does not exist at CONFDIR/private/key.pem a new key is generated unless -n, --never-create is specified.

> If the new account private key does not exist at CONFDIR/private/newkey.pem it is generated unless -n, --never-create is specified.

> The private key for the certificate is loaded from CONFDIR/private/DOMAIN/key.pem. If no such file exists, a new key is generated unless -n, --never-create is specified. 

Basically you need to place the key file in one of those locations based on what you want to do.
