### ISSUE TITLE
Works only on POSIX filesystems: hardlink required

### ISSUE THREAD

**Issue by kolbma** [ndilieto/uacme#53]
I am using a filesystem which does not support hard links.  
So the code like here:  

https://github.com/ndilieto/uacme/blob/7f1ffbda16147de5271ed08728a2ccb939964da0/uacme.c#L1180-L1186

to backup the current file fails and the `cert.pem.tmp` is left at its place, so I've to manually move `cert.pem.tmp` to `cert.pem`.

Similar for...

https://github.com/ndilieto/uacme/blob/7f1ffbda16147de5271ed08728a2ccb939964da0/uacme.c#L745-L757

Is it doable to copy the file to backup when link fails?

Like with code from here: https://stackoverflow.com/questions/2180079/how-can-i-copy-a-file-on-unix-using-c

**Comment by ndilieto** [comment]
I am not planning to support any non-POSIX system, sorry.
