### ISSUE TITLE
chain and fullchain.pem

### ISSUE THREAD

**Issue by Jeevhi** [ndilieto/uacme#54]
Hi,

I tried uacme and it gets cert and the key. However, it does not get chain and fullchain as done by certbot. 

Can you please add feature or let me know how to do it?

Thanks

**Comment by ndilieto** [comment]
uacme is not certbot. Read the documentation.

**Comment by moll** [comment]
Hey, @ndilieto. Thanks for maintaining uacme!

I've got the same question actually. I looked over the manpage, the README and searched the repo, but I didn't spot anything about the certificate chain. Is there documentation about it somewhere or is one supposed to obtain the chain out of band? I wonder how other ACME clients do that. Is fetching it part of the ACME spec?

Thanks!

**Comment by ndilieto** [comment]
By default ACME servers are supposed to serve the full chain, and that is what uacme saves to the cert file.

https://datatracker.ietf.org/doc/html/rfc8555#section-7.4.2

> The default format of the certificate is application/pem-certificate-chain

**Comment by moll** [comment]
Got it. Thanks, @ndilieto.
