### ISSUE TITLE
Best way to ensure cert.pem is world readable?

### ISSUE THREAD

**Issue by singpolyma** [ndilieto/uacme#55]
With my current setup every time it renews `cert.pem` is readable only by `root`.  Default `umask` on the system is `0022`

**Comment by ndilieto** [comment]
Which system are you on? If umask is 0022 this should not be happening because uacme always creates the new certificate with world readable permissions (S_IRUSR|S_IRGRP|S_IROTH, i.e. 444)

https://github.com/ndilieto/uacme/blob/64d1b3c260c782c037246ef63e16492f20c6fd9d/uacme.c#L1163

**Comment by singpolyma** [comment]
Thanks for this, I think I've managed to find the bug in my setup.  Sorry for the noise.
