### ISSUE TITLE
Password files

### ISSUE THREAD

**Issue by Xavantex** [ndilieto/uacme#72]
Not sure what the take or philosophy is around this, but have seen other implementations and support for encrypting keys with passwords/password-files, is it something that is within the scope of the project to enable usage of passwords/password-files?

Or perhaps there it is an intentional design-choice.

**Comment by ndilieto** [comment]
ACME stands for Automatic Certificate Management Environment. Automation would require keeping the password stored somewhere in the filesystem which defeats the point of encrypting the key and provides no additional security.
