### ISSUE TITLE
run hooks parallel

### ISSUE THREAD

**Issue by satan1st** [ndilieto/uacme#75]
I would like to have the hooks run parallel. Our DNS provider is quite slow and a change needs up to 20. min. This adds up pro domain.

> You haven't considered that having multiple hooks run in parallel will result in very problematic race conditions, for example multiple hooks changing the same webserver or DNS configuration at once.

Actually I have considered this and noticed the scripts currently can run in parallel. Because multiple certs can contain the same domain.

>  Hooks would need to implement their own locking mechanism to avoid this.

For http and dns challenges this is not a problem, because it's save to assume that the token/auth is different for each challenge.

For tls-alpn ualpn.c might needs some locking, but I would say it's required anyway.

**Comment by ndilieto** [comment]
I explained my reasons for rejecting your pull request and closed that discussion. Your insistence with this issue just earned you a ban.
