### ISSUE TITLE
How to request ocsp-must-staple on certificates

### ISSUE THREAD

**Issue by a1730** [ndilieto/uacme#8]
How do I pass ocsp-must-staple flag to uacme?
I grepped the source code but did not find this flag or the option.
I then looked at [go-acme/lego](https://github.com/go-acme/lego) specifically [this](https://github.com/go-acme/lego/blob/3edb75872df36444f95c25f88c6df325de89be11/certcrypto/crypto.go#L43-#L44) thinking that I would create a pull request but my C language skills are failing me.
What do you suggest?

**Comment by ndilieto** [comment]
With GnuTLS 3.5.8 or later it should be easy to add the necessary feature to the certificate request (look at the csr_gen function, in the crypto.c file)

```
gnutls_x509_tlsfeatures_t f;
gnutls_x509_tlsfeatures_init(&f);
gnutls_x509_tlsfeatures_add(f, 5);
gnutls_x509_crq_set_tlsfeatures(crq, f);
gnutls_x509_tlsfeatures_deinit(f);

```

**Comment by ndilieto** [comment]
Please, check if this patch (for mbedTLS only) works for you and let me know. If it does I will consider adding implementations for GnuTLS and OpenSSL.
[must-staple-patch.txt](https://github.com/ndilieto/uacme/files/3544946/must-staple-patch.txt)

**Comment by ndilieto** [comment]
> I noticed one difference in certificate key usage. LE's certificate shows a0 (Digital Signature, Key Encipherment) but the certificate created from uacme used 80 (Digital signatures).

This is the default key usage for a certificate request made by mbedTLS. The patch attached here makes key usage same as GnuTLS. Please let me know if it works.
[gnutls_key_usage_patch.txt](https://github.com/ndilieto/uacme/files/3548200/gnutls_key_usage_patch.txt)

**Comment by a1730** [comment]
Something is still missing. While Key encipherment is enabled for RSA certificates, this is not the case with ecc certificates. Please see attached images. The only command line difference when creating the certificates was the type parameter --type RCS vs --type EC.
![Capture](https://user-images.githubusercontent.com/1192408/64018654-015d3b00-cafb-11e9-88f8-7a7fa09fc759.PNG)

**Comment by cpu** [comment]
The key encipherment key usage bit doesn't make sense in the context of an EC key. As an example see this discussion: https://bugzilla.mozilla.org/show_bug.cgi?id=1560234

There is work underway (but not yet finalized) in the IETF to clarify this point w.r.t RFC 5480: https://datatracker.ietf.org/doc/draft-turner-5480-ku-clarifications/ by updating the text to say this explicitly:

```
3.  Updates to Section 3

   If the keyUsage extension is present in a certificate that indicates
   id-ecPublicKey as algorithm of AlgorithmIdentifier [RFC2986] in
   SubjectPublicKeyInfo, then following values MUST NOT be present:

     keyEncipherment; and
     dataEncipherment.

   If the keyUsage extension is present in a certificate that indicates
   id-ecDH or id-ecMQV in SubjectPublicKeyInfo, then the following
   values also MUST NOT be present:

     keyEncipherment; and
     dataEncipherment.
```

**Comment by ndilieto** [comment]
>  I have not been able to find a public site using ecc signature to compare against.

facebook.com and cloudflare.com have EC certs, and both only have the DigitalSignature bit. Note the lack of keyAgreement bit, which is dangerous: https://www.usenix.org/system/files/conference/woot15/woot15-paper-hlauschek.pdf

**Comment by a1730** [comment]
Got it. Thanks.
