### ISSUE TITLE
How to make uacme do dns-01 challenge

### ISSUE THREAD

**Issue by levaidaniel** [ndilieto/uacme#84]
I've been using `uacme(1)` for ages with *http-01* challenges and the stock `uacme.sh` helper script.
Recently I've been wanting to convert some domains to *dns-01* challenge, but for the life of me I cannot grasp how I should instruct `uacme(1)` to actually do a *dns-01* challenge, and with that setting the TYPE (2nd) parameter of the helper script to *dns-01* so I can use another helper script that handles *dns-01* challenges.

I've been reading the manual back and forth, but I just can't figure out what to do in order for `uacme(1)` to use *dns-01* challenge while asking for a certificate from letsencrypt.

I really hope I'm not missing something very-very obvious here, but I'm pretty sure I am, otherwise there would've surely been other questions like this...

Anyway, hope someone can hit me with a clue-stick.

Thanks,
Daniel

**Comment by ndilieto** [comment]
Just decline the undesired type of challenge by typing 'n' or - if you use a hook script, by returning non zero. Then uacme will propose the next type, in the same order as proposed by the acme server.
