### ISSUE TITLE
Unable to issue .tech domain

### ISSUE THREAD

**Issue by hmrodrigues** [ndilieto/uacme#86]
Hello,

When trying to issue a certificate for a .tech domain it shows a openssl error. I assume that it doesn't recognize .tech as a tld?
```

# uacme --bits 384 --hook /usr/share/uacme/ualpn.sh --must-staple --type EC issue www.openbit.tech
uacme: csr_load: openssl error:0480006C:PEM routines::no start line
uacme: csr_load: failed to load www.openbit.tech

```

If I replace .tech with .com it works as intended

**Comment by ndilieto** [comment]
You probably have a file 'www.openbit.tech' in the directory from which you are running uacme. That makes it think that you want to do 'issue CSRFILE', and of course 'www.openbit.tech' not being a CSR in PEM format makes it fail. Delete that file or run uacme from a different directory.

**Comment by hmrodrigues** [comment]
well that was easy :facepalm: sorry for the time consumed and thank you for the quick reply
