### ISSUE TITLE
Potential memory allocation issue in read-file.c

### ISSUE THREAD

**Issue by a1730** [ndilieto/uacme#9]
You may be interested that compiling uacme with gcc v7 and 
`Using built-in specs.
COLLECT_GCC=/opt/local/gcc7/bin/cc
COLLECT_LTO_WRAPPER=/opt/local/gcc7/libexec/gcc/x86_64-sun-solaris2.11/7.4.0/lto-wrapper
Target: x86_64-sun-solaris2.11
`
give diagnostic from realloc.
`read-file.c:119:14: warning: argument 2 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
           if (!(new_buf = realloc (buf, alloc)))
`

**Comment by ndilieto** [comment]
Does the attached patch fix the warning?

[fix-read-file-alloc-size-larger-than.txt](https://github.com/ndilieto/uacme/files/3549273/fix-read-file-alloc-size-larger-than.txt)
